✨  Implement git fixup shell function

diff --git a/dotfiles/sh_aliases b/dotfiles/sh_aliases
--- a/dotfiles/sh_aliases
+++ b/dotfiles/sh_aliases
@@ -52,6 +52,7 @@ asdf-outdated() {
   asdf update
   asdf plugin-update --all
   (asdf current > /dev/null) 2>&1 | awk '{print $1;}' | while read -r i; do asdf list-all ${i} > ${i}.versions; done
+  asdf list
   asdf current
 }
 
@@ -79,6 +80,23 @@ gstatistics() {
     printf "  Commits: %7s\n" "${commits_count}"
     git log --no-merges --author="$author" --after="$after" --before="$before" --pretty=tformat: --numstat | awk '{inserted+=$1; deleted+=$2;} END {printf "  Added:   %7s\n  Removed: %7s\n", inserted, deleted }'
   done
+}
+gfix() {
+  if (($# < 1)); then
+    log_error "Usage:\n";
+    echo "  gfix <git-sha>";
+    return 0;
+  fi
+
+  git_sha=$1;
+  echo "GIT SHA => '${git_sha}'"
+  git cat-file -t "${git_sha}"
+  if [[ $? -eq 0 ]]; then
+    echo "OK"
+    git commit --fixup ${git_sha} && git stash && git rebase -i --autosquash ${git_sha}~1 && git stash pop
+  else
+    log_error "Invalid git commit sha: '${git_sha}'";
+  fi
 }
 
 print_all_colors() {
